### ISSUE TITLE
Feature Request/add cml_import module

### ISSUE THREAD

**Issue by ksaegusa** [CiscoDevNet/ansible-cml#6]
Hi

I sometimes use the Import feature of CML to build my Lab. I would like to add the `cml_import` module as the current module does not allow that.

**Comment by stevenca** [comment]
cml_lab does this now.  Just specify a filename:

```
    - name: Create the lab
      cisco.cml.cml_lab:
        host: "{{ cml_host }}"
        user: "{{ cml_username }}"
        password: "{{ cml_password }}"
        lab: "{{ cml_lab }}"
        state: present
        file: "{{ cml_lab_file }}"
      register: results
```
